Added preferred layout name for creating new product page
Voog/design-firenze pull request #161
Opened 2021-03-11 14:40 UTC by robertpih

Related to #160

2021-05-07 06:26 UTC, tanelj requested changes
Manifest hetkel katki.

Manifest otsib komponenti `add-product-button`, mida ei ole.

2021-05-07 11:47 UTC, tanelj approved these changes

2021-05-10 06:40 UTC, tanelj approved these changes

2021-05-10 06:45 UTC, siimha approved these changes

2021-05-10 07:34 UTC, merged