Add option to hide date and comment block
Voog/design-firenze pull request #163
Opened 2021-05-11 12:41 UTC by pxska

1. Add option to hide author, date and comment block.
2. Use global, blog & article scope for given settings.
Closes #162.

Testimine:
* [x] Kontrollida, kas objekti tüübiks on toggle ja kas kuvatakse tooltipi (tõlkeid ei ole pealkirja, nupu nime ja tooltipi puhul kuvatud, kuna need peavad enne minema tõlkimisse).
```
menuItems: [
        {
          "titleI18n": "comments",
          "type": "toggle",
          "key": "show_comments",
          "tooltipI18n": "toggle_current_article_comments",
          "states": {
            "on": true,
            "off": false
          },
        }
      ],
```

* [x] Kontrollida, kas tulemus vastab [disainile](https://www.figma.com/file/PXwsuAGp6Fgnlc4MEf3nKQ6V/voog-hide-blog-elements) ja kas nupule vajutades muutub väärtus
* [x] Kontrollida, kas esmasel kasutamisel on kommentaarid, kuupäev ja autor kuvatud (võimalik, et mõnel mallil puuduvadki kommentaarid, autor või kuupäev). 
* [x] Kontrollida, kas toggle olek on esmasel kasutamisel enabled, kui väärtusi pole määratud
<img width="330" alt="screen shot 2018-10-19 at 09 31 12" src="https://user-images.githubusercontent.com/35253483/47201231-d2762480-d381-11e8-9f8d-559d8b621d92.png">

* [x] Kontrollida, kas väärtuse muutusel peidetakse/kuvatakse kommentaarid, kuupäev ja autor 
* [x] Kontrollida, kas blogilistingu vaates tehtud muudatused kehtivad ka artikli vaates, kui artikli vaates pole salvestatud väärtusi ja kas artikli vaates tehtud muudatused kirjutavad üle blogilistingu vaate väärtused 
* [ ] Kontrollida ka teisi objekti tüüpe, lisades sinna tooltipi ja jägides, et antud objekt toimiks korrektselt ja stiil oleks korras.

2021-05-13 11:13 UTC, siimha commented
Ma nüüd hakkasin mõtlema, et peagi tuleb meil mallidesse ka muid seaded ja võiks editori loogiga teha sarnaselt nuukile, et seaded tulevad vaid ühest nupust:
<img width="226" alt="Screenshot 2021-05-13 at 14 07 28" src="https://user-images.githubusercontent.com/35253483/118117880-d0b75500-b3f4-11eb-9475-76a1a3857503.png">

Komponendid, millest malli võtta:
1. `settings-popover `
2. `settings-blog-page`
3. `settings-article-page`

2021-05-14 10:11 UTC, tanelj requested changes

2021-05-14 10:11 UTC, tanelj commented on layouts/blog_article.tpl
> +                <time class="post-date{% if show_article_date == false %} hide-article-date{% endif %}{% if article_data_show_date_defined != false %} site-data{% endif %}" datetime="{{ article.creat
Siin on miskit ebakorrektset:
```
{% if article_data_show_date_defined != false %} site-data{% endif %}
```

Kas muutujat `article_data_show_date_defined` on üldse vaja?

Hetkel ei tööta ilma lehte reloadimata uue (ilma data seadeteta) artikli kuupäeva peitmine/näitamine.

* Lisa uus artikkel
* Ava artikli seaded
* Klikka "publishing date" peal (pida)
* => Visuaalselt ei juhtu midagi. Alles peale salvestamist ja reloadi läheb kuupäev peitu.

2021-05-21 11:15 UTC, siimha requested changes
Esmane tagasiside.

2021-05-21 11:15 UTC, siimha commented on layouts/blog___news.tpl
> +{% include "article-settings-variables" %}
See peab artiklite iteratsioonis olema, kus artikli objekt olemas.

2021-05-25 06:57 UTC, siimha requested changes

2021-05-25 06:57 UTC, siimha commented on javascripts/editmode.js
> +var debounce = function(func, wait, immediate) {
See tuleb sources -> javascripts kausta viia ja gruntiga siia copyda ja minimeerida.

2021-05-25 06:57 UTC, siimha commented on components/settings-blog-page.tpl
> +          if (data.show_comments == true) {
See ei tee listingu vaates midagi.

2021-05-25 06:57 UTC, siimha commented on components/settings-blog-page.tpl
> +            $articleDate.removeClass('hide-article-date');
Peidab ka artikli, milles on seadistatud, et see peab olema kuvatud.

2021-05-26 13:05 UTC, siimha requested changes

2021-05-26 13:05 UTC, siimha commented on assets/ico-tick.svg
> -<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 14 14"><path fill="#1B2124" d="M3.291 8.486c-.439-.314-.853-.47-1.239-.47-.352 0-.757.16-1.217.482s-.69.701-.69 1.135c0 .29
Lisa grunti seadistusele seadistus, mis keelab viewBoxi eemaldust:
```
// Minifies the image files.
imagemin: {
  build_images: {
    files: [{
      expand: true,
      cwd: 'sources/images/minify',
      src: '*.{png,jpg,gif}',
      dest: 'images/'
    }]
  },

  build_assets: {
    options: {
      svgoPlugins: [{removeViewBox: false}],
    },
    files: [{
      expand: true,
      cwd: 'sources/assets/minify',
      src: '*.svg',
      dest: 'assets/'
    }]
  }
},
```

2021-05-26 13:06 UTC, siimha commented on assets/ico-tick.svg
> -<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 14 14"><path fill="#1B2124" d="M3.291 8.486c-.439-.314-.853-.47-1.239-.47-.352 0-.757.16-1.217.482s-.69.701-.69 1.135c0 .29
Tundub, et `imagemin` uuem versioon on seda eemaldama hakanud.

2021-05-27 11:17 UTC, siimha requested changes
Paar asja tulid lisaks :)

2021-05-27 11:17 UTC, siimha commented on components/settings-editor-button.tpl
> +        <span class="edy-cbtn-ico"></span>
Stiilid ei ole õiged.
Hetkel:
![Screenshot 2021-05-27 at 14 08 00](https://user-images.githubusercontent.com/35253483/119816115-fcf2cb80-bef4-11eb-9c54-04a95dbdd0d1.png)

Nuuk:
![Screenshot 2021-05-27 at 14 06 00](https://user-images.githubusercontent.com/35253483/119816060-eb112880-bef4-11eb-85fd-6d387b244231.png)

2021-05-27 11:17 UTC, siimha commented on components/settings-editor-button.tpl
> +        <span class="edy-cbtn-ico"></span>
Lisaks võiks modal kinni minna, kui lehel klikatakse või salvestatakse ehk sel hetkel:
```
commit: function(data) {
  entityData.set(options.dataKey, data, {
    success: function() {
      if (options.noReload !== true) {
        window.location.reload();
      }
    }
  });
}

```

2021-05-27 11:17 UTC, siimha commented on components/settings-popover.tpl
> +    {% include "settings-editor" %}
`settings-editor` komponendi võiksid includida `edicy-tools` komponendis peale edicy-tools.js scripti.

2021-05-27 11:17 UTC, siimha commented on components/settings-popover.tpl
> +    {% include "settings-editor" %}
Selle tulemusena on ta [Editorjsblockis](https://www.voog.com/developers/markup/tags/editorjsblock), mille sisu lisatakse sinna, kus on Edicy objekt kindlalt saadav.

2021-05-31 10:08 UTC, siimha approved these changes
Ilus!

2021-05-31 10:24 UTC, siimha requested changes
Editmode scriptis on Grunt tegemata jäänud ja saab errori. Ehk [see](https://github.com/Voog/design-firenze/pull/163/files#diff-39679ffea09211123925e31564b82a0925ca71961f50d829b734a58107a8d407R33) on erinev.

2021-06-01 10:23 UTC, tanelj requested changes
Üks väike tagasiside veel. Muidu toimib kõik kenasti!

2021-06-02 06:29 UTC, pxska commented on layouts/blog___news.tpl
> +          <span class="add-button">{% addbutton %}</span>
Lahendasin selle ikkagi `{% if editmode %}` sisse panemisega – kui ma panen `{% addbutton %}` elemendile klassi, siis edicy-editor css failist tulenev `margin: 0 !important` kirjutab selle üle ja ei lase mul sellele nupule otse marginit määrata.

2021-06-02 14:03 UTC, tanelj approved these changes

2021-06-03 06:55 UTC, siimha approved these changes
Super töö!

2021-06-03 10:28 UTC, merged