Add various design improvements
Voog/design-firenze pull request #172
Opened 2022-05-18 07:24 UTC by PeeterPaal

- Use `object.og_image` method for OG image
- Add titles & tooltips to various content areas

Closes #170 
Closes #171

2022-05-19 06:50 UTC, tanelj requested changes
Nice, but some comments.

* [ ] Add title and tooltip to Article layout [additional_content](https://github.com/Voog/design-firenze/blob/master/layouts/blog_article.tpl#L54) area.

2022-05-19 06:50 UTC, tanelj commented on layouts/auto_generated_product.tpl
> +                    <div class="product-cross-page-info">
This div should not be displayed when there has no content:
E.g. `{% if editmode or gallery_content_size > 0 %}`

2022-05-19 06:50 UTC, tanelj commented on layouts/auto_generated_product.tpl
> +                      {% xcontent name="cross-page-info" title=cross_page_info_title title_tooltip=cross_page_info_title_tooltip %}
This is cross language content area and should be more specific to avoid conflicts.

E.g. `cross-page-info` -> `product-social`

2022-05-23 08:56 UTC, tanelj approved these changes
Nice!

2022-05-24 05:47 UTC, pxska approved these changes
Should there also be a title on the front page content area or is just the tooltip fine? 
<img width="590" alt="Screenshot 2022-05-24 at 08 46 13" src="https://user-images.githubusercontent.com/48313701/169957842-7be4ecb9-3f13-46c0-ad1e-3da1b8f5b1a2.png">

Otherwise check for long lines & looks good!

2022-05-24 07:47 UTC, robertpih approved these changes

2022-05-24 12:08 UTC, merged