Account for sale prices
Voog/design-firenze pull request #180
Opened 2023-11-20 12:51 UTC by piiamatsi

Account for sale prices on Auto-generated product pages. If product is on sale, then original price will be crossed out in both cases.

On Auto-generated product pages, setting buy buttons with_price has been updated to also take sale price into consideration. If product prices do not have any ranges, then price will not be displayed next to buy button.

Closes #179

2023-11-21 10:23 UTC, PeeterPaal requested changes
Prices on auto-gen product page buy buttons are currently displayed inside of the button, which should be fixed. 

Let's also add darkmode styles, as the Front page layout of this design utilizes light- and darkmode styles. Currently product widget prices are hidden when choosing a dark background on Front page.

2023-11-21 10:23 UTC, PeeterPaal commented on components/buy-button.tpl
> +      <div class="edy-buy-button-price-container"></div>
Due to buy button structure changes, this div has to be outside of `edy-buy-button` container. Currently prices appear inside buy button on auto-gen product pages.

<img width="479" alt="Screenshot 2023-11-21 at 12 17 18" src="https://github.com/Voog/design-firenze/assets/44435196/f8e8ae73-d2d9-4ae0-8728-c26aaa73e515">

2023-11-21 10:23 UTC, PeeterPaal commented on sources/stylesheets/_content-item.scss
> +    display: inline-block;
These styles should be indented a bit
```suggestion
    .product-price-original {
      display: inline-block;
      padding-right: 4px;
      opacity: .4;
    }

    .product-price-final {
      display: inline-block;
```

2023-11-23 08:42 UTC, tanelj approved these changes
Nice and works!

Only remark (old bug): `--button-background-color` variable is missing from Front page layout. Front page includes `template-cs-button-front` but this variable is included only to `template-cs-button`

2023-11-27 08:30 UTC, PeeterPaal requested changes
Darkmode styles are missing currently, otherwise looks good!

Front page of this design supports automatically adjusting colors for dark and light backgrounds. Buy button price and product widget prices should use `--light-primary` colour on front page in case of dark background.

<img width="899" alt="Screenshot 2023-11-27 at 10 27 47" src="https://github.com/Voog/design-firenze/assets/44435196/ba41bd9b-757f-49fd-b94e-26be7ce4cea3">

2023-11-28 10:15 UTC, PeeterPaal approved these changes
Looks good!

2023-11-28 11:22 UTC, merged